dist: trusty
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++-4.0
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0' ]
          packages: [ 'ninja-build', 'clang-4.0', 'libc++-dev' ]

    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++-4.0
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0' ]
          packages: [ 'ninja-build', 'clang-4.0', 'libc++-dev' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Debug COMPILER=g++-6
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-6' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release COMPILER=g++-6
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-6' ]

before_script:
  - mkdir build
  - cd build
  - echo $CMAKE_BUILD_TYPE
  - cmake -Werror=dev -GNinja -DCMAKE_CXX_COMPILER="$COMPILER" -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" ..

script:
  - ninja -v

after_success:
  - ./ZenUnitTests/ZenUnitTests

