dist: trusty
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - clang-5.0
            - libstdc++-7-dev

    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++-5.0
      addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - llvm-toolchain-trusty-5.0
         packages:
           - ninja-build
           - clang-5.0
           - libstdc++-7-dev

             #    - os: linux
             #      compiler: gcc
             #      env: CMAKE_BUILD_TYPE=Debug COMPILER=g++-7
             #      addons:
             #        apt:
             #          sources:
             #            - ubuntu-toolchain-r-test
             #          packages:
             #            - ninja-build
             #            - g++-7

             #    - os: linux
             #      compiler: gcc
             #      env: CMAKE_BUILD_TYPE=Release COMPILER=g++-7
             #      addons:
             #        apt:
             #          sources:
             #            - ubuntu-toolchain-r-test
             #          packages:
             #            - ninja-build
             #            - g++-7

before_script:
  - mkdir build
  - cd build
  - echo $CMAKE_BUILD_TYPE
  - cmake -GNinja .. -Werror=dev -DCMAKE_CXX_COMPILER="$COMPILER" -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE"

script:
  - ninja -v -j 1
  - ./ZenUnitTests/ZenUnitTests
  - ./ExamplesTests/ExamplesTests

