os: linux
dist: xenial
sudo: false
group: travis_latest
language: cpp
cache: ccache

git:
  depth: false

matrix:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++-6.0
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0' ]
          packages: [ 'ninja-build', 'clang-6.0', 'libjsoncpp0', 'libstdc++-7-dev', 'lcov' ]

    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++-6.0
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0' ]
          packages: [ 'ninja-build', 'clang-6.0', 'libjsoncpp0', 'libstdc++-7-dev', 'lcov' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Debug COMPILER=g++-8
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-8' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release COMPILER=g++-8
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-8' ]

          #- os: osx
          #      osx_image: xcode10
          #      compiler: clang
          #      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++
          #      before_install:
          #        - brew install ninja llvm

          #    - os: osx
          #      osx_image: xcode10
          #      compiler: clang
          #      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++
          #      before_install:
          #        - brew install ninja llvm

script:
  - apt search libjsoncpp
  - clang++ --version
  - g++ --version
  - cmake --version
  - ninja --version
  - python3 --version

  - mkdir build && cd build
  - cmake -GNinja .. -Werror=dev -DCMAKE_CXX_COMPILER="$COMPILER" -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE"
  - ninja -v

  - ./ZenMockTests/ZenMockTests
  - ./ZenMockExamples/ZenMockExamples
  - ./ZenUnitUtilsAndAssertionTests/ZenUnitUtilsAndAssertionTests
  - ./ZenUnitLibraryTests/ZenUnitLibraryTests
  - ./ZenUnitExamples/ZenUnitExamples

notifications:
  email: true

