dist: trusty
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - ninja-build
            - clang-6.0
            - libstdc++-7-dev

    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++-6.0
      addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - llvm-toolchain-trusty-6.0
         packages:
           - ninja-build
           - clang-6.0
           - libstdc++-7-dev

             #    - os: linux
             #      compiler: gcc
             #      env: CMAKE_BUILD_TYPE=Debug COMPILER=g++-7
             #      addons:
             #        apt:
             #          sources:
             #            - ubuntu-toolchain-r-test
             #          packages:
             #            - ninja-build
             #            - g++-7

             #    - os: linux
             #      compiler: gcc
             #      env: CMAKE_BUILD_TYPE=Release COMPILER=g++-7
             #      addons:
             #        apt:
             #          sources:
             #            - ubuntu-toolchain-r-test
             #          packages:
             #            - ninja-build
             #            - g++-7

script:
  - ./CloudJobs/TravisCIZenUnit.sh

