os: linux
dist: bionic
language: cpp
cache: ccache

git:
  depth: false

jobs:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++-9 CODE_COV_MODE=OFF
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'clang-9', 'libstdc++-9-dev' ]

    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++-9 CODE_COV_MODE=OFF
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'clang-9', 'libstdc++-9-dev' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Debug COMPILER=g++-9 CODE_COV_MODE=OFF
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-9' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release COMPILER=g++-9 CODE_COV_MODE=ON
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-9', 'lcov' ]

    #- os: osx
    #      osx_image: xcode10
    #      compiler: clang
    #      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++
    #      before_install:
    #        - brew install ninja llvm

    #    - os: osx
    #      osx_image: xcode10
    #      compiler: clang
    #      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++
    #      before_install:
    #        - brew install ninja llvm

script:
   - ./TravisScripts/travis_script.sh

after_success:
   - ./TravisScripts/travis_after_success.sh

notifications:
  email: true
