os: linux
dist: bionic
language: cpp
cache: ccache
sudo: false

git:
  depth: false

matrix:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++-6.0 CODE_COV_MODE=OFF
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0' ]
          packages: [ 'ninja-build', 'clang-6.0', 'libstdc++-7-dev' ]

    - os: linux
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++-6.0 CODE_COV_MODE=OFF
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0' ]
          packages: [ 'ninja-build', 'clang-6.0', 'libstdc++-7-dev' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Debug COMPILER=g++-8 CODE_COV_MODE=OFF
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-8' ]

    - os: linux
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release COMPILER=g++-8 CODE_COV_MODE=ON
      addons:
        apt:
          update: true
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'ninja-build', 'g++-8', 'lcov' ]

          #- os: osx
          #      osx_image: xcode10
          #      compiler: clang
          #      env: CMAKE_BUILD_TYPE=Debug COMPILER=clang++
          #      before_install:
          #        - brew install ninja llvm

          #    - os: osx
          #      osx_image: xcode10
          #      compiler: clang
          #      env: CMAKE_BUILD_TYPE=Release COMPILER=clang++
          #      before_install:
          #        - brew install ninja llvm

script:
   - ./CloudJobs/travis_script.sh

after_success:
   - ./CloudJobs/travis_after_success.sh

notifications:
  email: true

