shallow_clone: true

image:
    - Visual Studio 2017
    - Visual Studio 2017 Preview
    - Visual Studio 2019 Preview

environment:
   matrix:
      - generator: "Visual Studio 15 2017"

configuration:
   - Debug
   - Release

platform:
   - x64
   - Win32

before_build:
   - cmake -A %platform% -G "%generator%" .

build_script:
   - cmake --build . --config %configuration% -- /m

