image: Visual Studio 2017

build_script:
  - cmake -G"Visual Studio 15 2017 Win64"
  - msbuild ZenUnit.sln /p:Configuration=Debug /m
  - msbuild ZenUnit.sln /p:Configuration=Release /m
  - cd ZenUnitHelloWorld
  - cmake -G"Visual Studio 15 2017 Win64"
  - msbuild Executable.sln /p:configuration=Debug /m
  - msbuild Executable.sln /p:Configuration=Release /m

