image: Visual Studio 2017

build_script:
  - cmake -G"Visual Studio 15 2017 Win64"
  - msbuild ZenUnit.sln /p:Configuration=Debug
  - msbuild ZenUnit.sln /p:Configuration=Release
  - msbuild ZenUnitHelloWorld\Executable.sln /p:configuration=Debug
  - msbuild ZenUnitHelloWorld\Executable.sln /p:Configuration=Release

