image: Visual Studio 2017 Preview
shallow_clone: true

build_script:
  - curl https://raw.githubusercontent.com/NeilJustice/ZenMock/master/ZenMock/ZenMock.h -o ZenMock.h
  - cmake -G"Visual Studio 15 2017 Win64"
  - msbuild ZenUnit.sln /p:Configuration=Debug /p:Platform=x64 /m
  - msbuild ZenUnit.sln /p:Configuration=Release /p:Platform=x64 /m

