shallow_clone: true

environment:
   matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        generator: "Visual Studio 15 2017"
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 Preview
        generator: "Visual Studio 15 2017 Preview"
        
platform:
   - x64
   - Win32    

configuration:
   - Debug
   - Release

before_build:
   - curl https://raw.githubusercontent.com/NeilJustice/ZenMock/master/ZenMock/ZenMock.h -o ZenMock.h
   - cmake -A %platform% -G "%generator%"

build_script:
   - cmake --build . --config %configuration% -- /m
